# names of the keys correspond to the names of the toolbar images

toolb.admin.config=Administrasi
toolb.chart.config=Atur Grafik
toolb.chart=Lihat Grafik
toolb.cube=Navigator Cube
toolb.debug=Form Debug
toolb.excel.config=Atur Export Excel
toolb.excel=Export Excel
toolb.filter=Filter Data
toolb.hide.spans=Sembunyikan Gabungan
toolb.level.style=Tampilkan Parent
toolb.mdx.edit=Editor MDX
toolb.member.selection=Detail Member
toolb.navi.member=Drill Member
toolb.navi.position=Drill Posisi
toolb.navi.replace=Drill Replace
toolb.navi.drillthru=Drill Through
toolb.non.empty=Hapus Baris Kosong
toolb.param=Parameter Laporan
toolb.print.config=Atur Cetak
toolb.print=Export PDF
toolb.reload=Muat Ulang
toolb.reset.query=Beranda
toolb.properties=Lihat Properti
toolb.properties.config=Pilih Properti
toolb.sort.asc=Atur Urutan
toolb.swap.axes=Tukar Axis
toolb.table.config=Atur Tabel
toolb.table=Lihat Tabel
toolb.admin.refresh=Muat Repository
toolb.admin.sysvars=Lihat Variabel
toolb.bookmark=Simpan Bookmark
toolb.save=Simpan Tampilan
toolb.mdxparam=Ubah Parameter
toolb.auditlog=Lihat Audit Log
